# Generated by Django 4.1.5 on 2023-10-03 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='roll_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='section',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='student_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='details',
            name='year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
