# Generated by Django 4.1.5 on 2023-10-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_details_roll_number_alter_details_section_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='section',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
