# Generated by Django 4.1.5 on 2023-10-03 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_details_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='FullCollege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(max_length=10, null=True)),
                ('student_name', models.CharField(max_length=200, null=True)),
                ('year', models.CharField(max_length=100, null=True)),
                ('section', models.CharField(max_length=100, null=True)),
                ('title', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
